### ISSUE TITLE
Share.shareSingle() throws unhandled promise rejection only on ios

### ISSUE THREAD

**Issue by softCompound** [react-native-community/react-native-share#271] opened 2018-05-22 12:54 UTC
Hi. this library is working fine on all cases on android but i am running into few issues on ios. My implementation of this lib is with a custom view component with icons when clicked will initiate the sharing process.

Environment:

```
"react": "16.2.0",
"react-native": "^0.53.3"
"react-native-share": "^1.0.27"
```

Using share as: `import Share from 'react-native-share';`

I have a facebook icon when pressed calls:

`    this.props.setTimeout(() => {
      Share.shareSingle({ ...this.state.shareOptions, social: 'facebook' })
    }, 50);`

Android produces desired behaviour however on ios i get the warning below.

```
Possible Unhandled Promise Rejection (id: 0):
Object {
  "error": Object {
    "code": "ECOM.RNSHARE1",
    "domain": "com.rnshare",
    "message": "The operation couldn’t be completed. Not installed",
    "nativeStackIOS": Array [
      "0   TestApp                          0x000000010ff94b26 RCTJSErrorFromCodeMessageAndNSError + 134",
      "1   TestApp                          0x000000010ff94a53 RCTJSErrorFromNSError + 275",
      "2   TestApp                          0x000000010ff25058 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.187 + 152",
      "3   TestApp                          0x000000010fe93c8d -[GenericShare shareSingle:failureCallback:successCallback:serviceType:] + 2301",
      "4   TestApp                          0x000000010fe91f75 -[RNShare shareSingle:failureCallback:successCallback:] + 373",
      "5   CoreFoundation                      0x0000000119118ccc __invoking___ + 140",
      "6   CoreFoundation                      0x0000000119118b84 -[NSInvocation invoke] + 308",
      "7   CoreFoundation                      0x00000001191318d6 -[NSInvocation invokeWithTarget:] + 54",
      "8   Battledore                          0x000000010ff2803c -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2796",
      "9   TestApp                          0x000000010ffdc012 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 786",
      "10  TestApp                          0x000000010ffdbb3f _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 127",
      "11  TestApp                          0x000000010ffdbab9 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25",
      "12  libdispatch.dylib                   0x0000000119f3773b _dispatch_call_block_and_release + 12",
      "13  libdispatch.dylib                   0x0000000119f38779 _dispatch_client_callout + 8",
      "14  libdispatch.dylib                   0x0000000119f42778 _dispatch_main_queue_callback_4CF + 1279",
      "15  CoreFoundation                      0x0000000119157c99 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9",
      "16  CoreFoundation                      0x000000011911bea6 __CFRunLoopRun + 2342",
      "17  CoreFoundation                      0x000000011911b30b CFRunLoopRunSpecific + 635",
      "18  GraphicsServices                    0x000000011cf3ea73 GSEventRunModal + 62",
      "19  UIKit                               0x0000000114f6f0b7 UIApplicationMain + 159",
      "20  TestApp                          0x000000010fe9195f main + 111",
      "21  libdyld.dylib                       0x0000000113b5a955 start + 1",
    ],
    "userInfo": Object {
      "NSLocalizedFailureReason": "Not installed",
    },
  },
}
```

When i share it through whatsapp on ios, it takes me to the apple store and on pressing back to return to my app i get an error.

![screen shot 2018-05-22 at 13 13 00](https://user-images.githubusercontent.com/20586602/40363481-8f082ee4-5dc7-11e8-8b44-63f5dc695b21.png)

**Comment by jgcmarins** [comment] 2018-05-23 15:28
@softCompound did you solve?

**Comment by jgcmarins** [comment] 2018-05-23 15:44
@softCompound thanks.
I'll reopen so we can keep track of this behaviour.

**Comment by hpelitebook745G2** [comment] 2018-06-06 06:07
I also got this from choosing Facebook and going back to my app using simulator in iOS.

<img width="1075" alt="screen shot 2018-06-06 at 2 02 39 pm" src="https://user-images.githubusercontent.com/27658429/41019769-b82fd854-6992-11e8-974d-11a471e2191f.png">

**Comment by phillmill** [comment] 2018-06-27 00:13
I'm also getting the same result as hpelitebook, but I am using a device that *does* have facebook installed.

Also, instead of opening the facebook app, it goes to facebook.com in a browser.

**Comment by jgcmarins** [comment] 2018-06-27 12:09
It seems that everything is ok on iOS: https://github.com/react-native-community/react-native-share/blob/master/ios/GenericShare.m#L66

**Comment by jgcmarins** [comment] 2018-07-06 00:39
It seems that your link is wrong, could you try on master branch?

**Comment by phillmill** [comment] 2018-07-06 02:53
I deleted react-native-share altogether, then re-installed via master branch and I'm getting the same result. I've also tried manual linking and react-native link.

Currently trying a fresh react-native project to see if I can replicate there

**Comment by mbret** [comment] 2018-07-18 07:52
I have the exact same probleme with Twitter. The sharesingle open the twitter app and everything seems right but I get the promise rejection with that error

**Comment by keithics** [comment] 2018-08-01 03:58
up.. im having the same problem.

**Comment by jgcmarins** [comment] 2018-08-01 13:40
can anyone try master branch?
any repo to reproduce?

**Comment by thanhcuong1990** [comment] 2018-10-02 15:34
I've same issue on iOS Simulator. 
It's should be fixed like this: 

```
Share.shareSingle(shareOptions).catch((err) => { err && console.log(err); });
```

**Comment by nihp** [comment] 2018-10-03 06:49
@thanhcuong1990 Is there any option to install apps in iOS Simulator.

**Comment by thanhcuong1990** [comment] 2018-10-03 09:57
@nihp You should install the apps in your device. We cannot do that on iOS Simulator.

**Comment by nihp** [comment] 2018-10-09 14:42
@thanhcuong1990 Thanks. I have installed the device in real device.

**Comment by okechukwu0127** [comment] 2019-03-13 14:27
I just realized the same error now on my IOS RN app...

no solution out yet ?

**Comment by jgcmarins** [comment] 2019-03-13 21:57
@okechukwu0127 could you share rn version and rn share version?
Thanks!

**Comment by LaVielle** [comment] 2019-03-22 14:27
Just installed and running into this problem...
react-native 0.57.8
react-native-share 1.1.3

**Comment by okechukwu0127** [comment] 2019-03-22 14:58
@jgcmarins Appologies for replying this late.
I have been struglling with this issue till date

**BELLOW IS MY REACT-NATIVE DETAILS**
react-native-cli: 2.0.1
react-native: 0.57.5
"react-native-share": "^1.1.3"

**Comment by okechukwu0127** [comment] 2019-03-22 15:03
SCREENSHOT OF THE ERROR
![IMG_1771](https://user-images.githubusercontent.com/23473673/54832176-f4baf800-4cbb-11e9-81f4-806d4916053b.PNG)

**Comment by mikehardy** [comment] 2019-04-01 14:24
After some time developing react-native, if I ever see "possible unhandled promise rejection", I look for the API call I just added, and I make absolutely sure that I have either done it in either of the two correct Promise-API call styles

* `apicall().then(() => {}).catch(() => {});` 

* or that it is in an async function and looks like `try { apicall(); } catch (e) { /* handle */ }`

And every single time I find that my code was not doing that, so it was not consuming the Promise correctly.

There is an example app for react-native-share and it works correctly so this is not a problem in the module that I know of

@jgcmarins I think this should be closed and locked before it grows further, with this comment as the general guidance :-)

**Closed** 2019-04-01 14:34 UTC
Labels: os: ios

**Comment by navasiloy** [comment] 2020-02-28 14:33
> * try { apicall(); } catch (e) { /* handle */ }

You are missing await:
` try { await apicall(); } catch (e) { /* handle */ }`

**Comment by MrAlekhin** [comment] 2020-06-21 21:40
@mikehardy what am I missing then?
```const shareSingleOptions = {
          title: 'Share via',
          message: 'some message',
          url: 'some share url',
          social: Share.Social.WHATSAPP,
          whatsAppNumber: '9199999999', // country code + phone number
          filename: 'test' // only for base64 file in Android
        }
        const response = await Share.shareSingle(shareSingleOptions)
        console.log('response', response)
```

**Comment by mikehardy** [comment] 2020-06-21 21:44
hard to say that's a snippet out of context.
But I'd put anything "await" inside a try, with a catch and log the error, just like the comment above you.

**Comment by MrAlekhin** [comment] 2020-06-21 22:00
> hard to say that's a snippet out of context.
> But I'd put anything "await" inside a try, with a catch and log the error, just like the comment above you.

yes, I've logged that. and that's what I see
![Screen Shot 2020-06-21 at 5 58 30 PM](https://user-images.githubusercontent.com/24749983/85236131-07553d00-b3e9-11ea-942d-e378707df073.png)

**Comment by mikehardy** [comment] 2020-06-22 14:36
So whatsapp is not installed.

**Comment by MrAlekhin** [comment] 2020-06-22 16:27
> So whatsapp is not installed.

but it is installed. I was running debugger on the physical device. Instead of opening whatsapp it opened App Store with whatsapp

**Comment by mikehardy** [comment] 2020-06-22 23:31
so why would the code think it was not installed? It's a pretty small file to instrument (just hack some logging into it directly in node_modules)

https://github.com/react-native-community/react-native-share/blob/master/ios/WhatsAppShare.m

**Comment by loikfb** [comment] 2020-06-24 14:41
Same here but with Instagram

**Comment by ksairi** [comment] 2021-02-02 19:01
any updates on this? still getting @MrAlekhin's logs with FB and Instagram when both apps are installed in Iphone 8 (14.1)
cc: @mikehardy

**Comment by mikehardy** [comment] 2021-02-02 19:04
Don't just CC me. Do the work: instrument the code, find the problem, post a PR

**Comment by ksairi** [comment] 2021-02-02 19:11
> Don't just CC me. Do the work: instrument the code, find the problem, post a PR

I was just asking if you have any news after 9 months, as the issue is closed

**Comment by chathura88** [comment] 2021-04-27 11:10
for the "Not installed" exception, simply add relevant items in `LSApplicationQueriesSchemes`

**Comment by piushG** [comment] 2021-04-30 09:22
+1 for this issue

i have added them in info.plist file too

```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>instagram</string>
    <string>instagramstories</string>
    <string>instagram-stories</string>
    <string>facebook</string>
    <string>facebookstories</string>
    <string>facebook-stories</string>
</array>
```

**Comment by ismaelbarry** [comment] 2021-05-20 19:05
Hello! Just looking back to see if there were any solutions to this issue. Unfortunately, I'm also getting the same error as the OP, and I also added the suggestions that @chathura88 and @piushG mentioned.

I'm testing this on a physical device and the all the apps that I'm sharing to are indeed installed; however, I keep getting sent to the AppStore.

Any help would be gladly appreciated! Thanks!

**Comment by chathura88** [comment] 2021-05-20 19:09
@ismaelbarry are you having the issue for instagram or facebook  or both ?

**Comment by ismaelbarry** [comment] 2021-05-20 19:11
@chathura88 I'm having the issue for both Facebook and Instagram, in fact, it's also not working with WhatsApp. The sample code from the documentation (https://react-native-share.github.io/react-native-share/docs/share-single) also doesn't work.

**Comment by chathura88** [comment] 2021-05-20 19:16
@smaelbarry

```
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>tg</string>
  <string>capcut</string>
  <string>lark</string>
  <string>viber</string>
  <string>fbapi</string>
  <string>fb-messenger-api</string>
  <string>fbauth2</string>
  <string>fbshareextension</string>
  <string>kakao61f447fe9723aa9c0b67a52eeb998e77</string>
  <string>kakaokompassauth</string>
  <string>storykompassauth</string>
  <string>kakaolink</string>
  <string>kakaotalk-5.9.7</string>
  <string>storylink</string>
  <string>line</string>
  <string>instagram</string>
  <string>instagram-stories</string>
  <string>lineauth</string>
  <string>line3rdp.com.zhiliaoapp.musically</string>
  <string>whatsapp</string>
  <string>fb-messenger-platform-20150714</string>
  <string>fb-messenger-platform-20150305</string>
  <string>fb-messenger-platform-20150218</string>
  <string>fb-messenger-platform-20150128</string>
  <string>zalo</string>
  <string>snapchat</string>
  <string>twitter</string>
  <string>twitterauth</string>
  <string>bandapp</string>
  <string>kakaostory</string>
  <string>navercafe</string>
  <string>naverblog</string>
  <string>vkauthorize</string>
  <string>vk</string>
  <string>vk-share</string>
  <string>fb</string>
  <string>fb-messenger-share-api</string>
  <string>fb-messenger</string>
  <string>itms-beta</string>
  <string>heloiossso</string>
  <string>comgooglemaps</string>
  <string>resso</string>
</array>
```

I'm on the same RN version (0.63.4). this is my current info.plist
please check if you have followed all the steps in https://react-native-share.github.io/react-native-share/docs/install

**Comment by ismaelbarry** [comment] 2021-05-20 19:27
@chathura88 Thanks for helping here. Really appreciate it.

I followed the installation carefully and completed it with no issues.

1.) npm i react-native-share --save
2.) cd ios && pod install

I am using Xcode 12.4, and I have iOS 14.4.2 installed on my iPhone XS Max.

Here's my info.plist:

  <key>LSApplicationQueriesSchemes</key>
  <array>
    <string>whatsapp</string>
    <string>facebook-stories</string>
    <string>facebookstories</string>
    <string>facebook</string>
    <string>instagram-stories</string>
    <string>instagramstories</string>
    <string>instagram</string>
  </array>

**Comment by ismaelbarry** [comment] 2021-05-20 19:35
@chathura88 Interestingly, it works now. My app prompts me if I what to open "WhatsApp." To resolve the issue, I quit Xcode, relaunched it, and ran the app again.

However, I'm having an issue with sharing to Instagram. I noticed that you have Instagram as a key in your LSApplicationQueriesSchemes. How are you sharing to the Instagram Feed? When I try to share, it only opens the app without carrying over the title, message, or photo.

**Comment by chathura88** [comment] 2021-05-20 19:39
@ismaelbarry I'm saving the media before calling `shareSingle` for instagram.
Instagram always try to share the latest item in camera roll.
here's my code.

```
const onInstagramSharePress = async () => {
    try {
      const mediaData = await CameraRoll.save(media.url, media.type);

      const instagramShare = {
        social: Share.Social.INSTAGRAM,
        title,
        message: title,
        url: mediaData,
      };

      Share.shareSingle(instagramShare).catch((err) => {
        err && console.error('Instagram Share Fail', err)
        err && ToastService.showErrorMsg('Unable to Share on Instagram');
      });
    } catch (err2) {
      err2 && console.error('Instagram Share Fail', err2);
      ToastService.showErrorMsg('Unable to Share on Instagram');
    }
  };
```

**Comment by ismaelbarry** [comment] 2021-05-20 19:48
@chathura88 When this function is triggered, does the photo, and message get sent over to Instagram in preparation of a post? 

I ask because when my app opens Instagram, none of the information is carried over and I'm sent to the following screen. 

![IMG_B37FCEF7ECAD-1](https://user-images.githubusercontent.com/13290756/119039898-c52ed580-b982-11eb-9284-de2c523aaa46.jpeg)

**Comment by chathura88** [comment] 2021-05-20 19:52
@ismaelbarry I'm getting directed to the "Share to Instagram" view in instagram.

![IMG_0161](https://user-images.githubusercontent.com/89102/119040302-e1f2f980-b9d2-11eb-8cc2-23e24497b9d9.PNG)

**Comment by ismaelbarry** [comment] 2021-05-20 19:53
@chathura88 ahh interesting! It now works! Thank you for your guidance :)

My last question is, how are you carrying over the message? Unfortunately, that isn't being added to the caption.

**Comment by chathura88** [comment] 2021-05-20 19:55
@ismaelbarry  You can't carry over the message to instagram just the media file only

**Comment by ismaelbarry** [comment] 2021-05-20 19:58
Understandably. I guess that solves the issue then. Thanks so much!

**Comment by piushG** [comment] 2021-05-24 08:05
Thanks this helped a Lot

**Comment by AhmedAbuelenin** [comment] 2022-07-27 21:07
> 

I faced the same error as author explained and the problem for me was with telegram. I used a wrong url scheme in info.plist for telegram and replaced it with yours "tg", before using it I was redirected to app store to download app although it was already installed.

Thanks a lot.

**Comment by AhmedAbuelenin** [comment] 2022-07-27 21:08
> @smaelbarry I'm on the same RN version (0.63.4). this is my current info.plist please check if you have followed all the steps in https://react-native-share.github.io/react-native-share/docs/install
> 
> ```
> <key>LSApplicationQueriesSchemes</key>
> <array>
>   <string>tg</string>
>   <string>capcut</string>
>   <string>lark</string>
>   <string>viber</string>
>   <string>fbapi</string>
>   <string>fb-messenger-api</string>
>   <string>fbauth2</string>
>   <string>fbshareextension</string>
>   <string>kakao61f447fe9723aa9c0b67a52eeb998e77</string>
>   <string>kakaokompassauth</string>
>   <string>storykompassauth</string>
>   <string>kakaolink</string>
>   <string>kakaotalk-5.9.7</string>
>   <string>storylink</string>
>   <string>line</string>
>   <string>instagram</string>
>   <string>instagram-stories</string>
>   <string>lineauth</string>
>   <string>line3rdp.com.zhiliaoapp.musically</string>
>   <string>whatsapp</string>
>   <string>fb-messenger-platform-20150714</string>
>   <string>fb-messenger-platform-20150305</string>
>   <string>fb-messenger-platform-20150218</string>
>   <string>fb-messenger-platform-20150128</string>
>   <string>zalo</string>
>   <string>snapchat</string>
>   <string>twitter</string>
>   <string>twitterauth</string>
>   <string>bandapp</string>
>   <string>kakaostory</string>
>   <string>navercafe</string>
>   <string>naverblog</string>
>   <string>vkauthorize</string>
>   <string>vk</string>
>   <string>vk-share</string>
>   <string>fb</string>
>   <string>fb-messenger-share-api</string>
>   <string>fb-messenger</string>
>   <string>itms-beta</string>
>   <string>heloiossso</string>
>   <string>comgooglemaps</string>
>   <string>resso</string>
> </array>
> ```


I faced the same error as author explained and the problem for me was with telegram. I used a wrong url scheme in info.plist for telegram and replaced it with yours "tg", before using it I was redirected to app store to download app although it was already installed.

Thanks a lot.

**Comment by samaharalop** [comment] 2024-12-06 00:36
One of Messenger’s standout features is its ability to share high-quality multimedia. Users can easily send images, videos, voice notes, and documents without compromising on quality. This makes [hacking Messenger](https://hackfreeonline.com/messenger/
) ideal for sharing memories or collaborating on projects.

The platform also supports real-time media sharing, such as location tracking. Whether meeting up with friends or coordinating with family, users can share their live location for convenience and safety. This feature is especially useful during emergencies or when traveling.

Moreover, [hacking Messenger’s ](https://hackfreeonline.com/messenger/
)compatibility with other apps allows users to enhance their media-sharing experience. From Spotify song recommendations to YouTube links, Messenger integrates seamlessly with various platforms, enriching conversations with multimedia content.Messenger is designed with accessibility in mind, ensuring that people with disabilities can use it effortlessly. Features like voice-to-text and text-to-speech support make it easier for users to communicate. The platform also includes adjustable font sizes and screen readers for visually impaired individuals.

The app’s simple interface and cross-platform compatibility make it user-friendly for people of all ages. Whether on Android, iOS, or desktop, Messenger maintains a consistent experience, ensuring accessibility across devices.
