### ISSUE TITLE
Share sheet not working

### ISSUE THREAD

**Issue by SalviShahzad** [react-native-community/react-native-share#323] opened 2018-07-30 13:03 UTC
I moved from version 1.0.27 to 1.1.0, since then share sheet is not opening up when we click on "share UI component"

**Comment by jgcmarins** [comment] 2018-07-30 13:32
Is there any error message?
iOS or Android?
Did you follow README? There were improvements on linking.

**Comment by SalviShahzad** [comment] 2018-07-31 04:26
No there is no error message.
Platform is ios. I have not tested for android yet.
Yes I followed README and cross verified all the manual steps on both the platforms and did changes that were missing.

**Comment by SalviShahzad** [comment] 2018-07-31 10:59
On android I am getting this error: Error type 3
Error: Activity class {com.my_project_name/com.my_project_name.MainActivity} does not exist.

**Comment by jgcmarins** [comment] 2018-07-31 11:42
considering this error message, looks like it's a problem with your link

**Comment by SalviShahzad** [comment] 2018-07-31 12:08
I followed all the steps mentioned in manual

**Comment by yeomann** [comment] 2018-08-02 08:46
I am like sure that your problem is of linking. for android I created a test repo https://github.com/yeomann/react-native-share-android-test 

it uses latest React native and Gradle 3+ and manuall linking. Please follow the configs mentioned in readme and see the link repo for example.

**Comment by yeomann** [comment] 2018-08-04 13:09
closing assuming the issue might have been resolved. Please feel free to open it again @SalviShahzad

**Closed by yeomann** 2018-08-04 13:09 UTC
Labels: needs more info

**Comment by sathvik12345** [comment] 2019-02-07 13:37
react-native version: 0.50.4
react-native-share: 1.1.0
 
i tried with 1.1.2 but i was not able to open Share sheet 

i cant upgrade latest version of react-native-share too..

**Comment by mikeKane** [comment] 2019-06-12 17:34
Bump. 

I am on the latest and it will not open a share sheet on iOS for me either

**Comment by mikehardy** [comment] 2019-06-12 20:14
@mikeKane can you reproduce this using the example app?
