### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by guillaume-tgl** [react-native-community/react-native-share#540] opened 2019-07-04 12:54 UTC
## Ask your Question
Any plan to migrate to AndroidX now that it's a standard in react-native 0.60?

**Comment by mikehardy** [comment] 2019-07-04 12:57
The library should certainly update, all libraries need to, but it's my understanding that https://github.com/mikehardy/jetifier will allow you to use the library regardless of your apps AndroidX conversion status or the libraries AndroidX conversion status

Since converting the library without jetifier working well with it implies orphaning current users of the library that cannot migrate, I'm much more interested in success reports (or bug reports!) about compatibility with jetifier + RN0.60 + AndroidX and jetifier -r + RN0.59 + this library as AndroidX then I am about converting immediately.

Once compatibility is confirmed in both directions, then it's largely inconsequential and could happen any time

**Comment by guillaume-tgl** [comment] 2019-07-04 13:48
Thanks for the quick and detailed answer.
I confirm I was able to use this library with jetifier and RN0.60 so you're right, there's no need to hurry :)

**Comment by se-bastiaan** [comment] 2019-07-11 20:18
Maybe it is good to keep this issue open for reference.

**Comment by mikehardy** [comment] 2019-07-11 20:59
@se-bastiaan it is pinned currently, that puts it at the top of the page

**Comment by se-bastiaan** [comment] 2019-07-12 07:39
That doesn't mean that the issue is done, right?

**Comment by jgcmarins** [comment] 2019-07-16 15:08
### References
- https://github.com/react-native-community/react-native-camera/pull/2306

**Comment by MateusAndrade** [comment] 2019-07-16 15:27
Anyone tested react-native-share with Android X/react-native 0.60?

**Comment by jgcmarins** [comment] 2019-07-16 18:50
I guess that @Thomazella is working on it

**Comment by Thomazella** [comment] 2019-07-16 21:09
Correct I'll post a status update in the next few days. :D

**Comment by sibelius** [comment] 2019-07-16 21:24
`npx jetifier`

**Comment by kimihiro64** [comment] 2019-07-16 22:46
I ran npx jetifier, it reported 1041 files forward jetified, but fails sync with:
ERROR: Unable to resolve dependency for ':react-native-share@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:28.0.0.

Not sure what to do from there... I can see the line that generates it in react-native-share's build.gradle, implementation "com.android.support:appcompat-v7:${safeExtGet('supportLibVersion', '28.0.0')}"... Was that supposed to get jetified to something else and it just didn't work?

**Comment by oleksandr-dziuban** [comment] 2019-07-17 13:00
@MateusAndrade Hello, I have tested t
react-native-share on a production project with react-native@0.60.3. iOS works fine in debug/release build, but Android fails in release build mode.
Please check this issue: 
https://github.com/react-native-community/react-native-share/issues/549

**Comment by mikehardy** [comment] 2019-07-19 00:59
@kimihiro64 yeah - you also need to change your supportLibVersion, and note that https://github.com/mikehardy/jetifier#module-maintainers item 2 here for module name overrides might be useful for people as long as AndroidX changes are being made

**Comment by MateusAndrade** [comment] 2019-07-21 20:46
#550

**Comment by sibelius** [comment] 2019-07-22 14:38
fixed on v2

**Closed by sibelius** 2019-07-22 14:38 UTC
Labels: bug, help wanted, os: android, question
