### ISSUE TITLE
iOS Yellow box: Class was not exported

### ISSUE THREAD

**Issue by gaykov** [react-native-community/react-native-share#359] opened 2018-09-04 08:46 UTC
### Steps to reproduce
1. Install and link the library
2. Open your app

### Expected behaviour
The app shouldn't throw the yellow boxes

### Actual behaviour
Now the following warnings are shown:
![image](https://user-images.githubusercontent.com/9068073/45020527-e36c1000-b037-11e8-9c97-8b7a2528582f.png)

### Environment
- **React Native version**: `0.56.0`
- **React Native platform + platform version**: `iOS 11.4`

### react-native-share
**Version**: `1.1.1`

### Link to repo (highly encouraged)
https://github.com/insiderdev/minimal-quotes

**Comment by thanhcuong1990** [comment] 2018-09-04 09:55
I've got the same issue. 

_Environment_
```
react-native: 0.55.4
iOS: 11.4
react-native-share: 1.1.1
```

**Comment by eminsr** [comment] 2018-09-18 15:00
Duplicate of #329

**Comment by jgcmarins** [comment] 2018-09-18 15:11
thanks

**Closed by jgcmarins** 2018-09-18 15:11 UTC
Labels: os: ios
