### ISSUE TITLE
Can't find Wechat sharing button, any reason why?

### ISSUE THREAD

**Issue by sulliwane** [react-native-community/react-native-share#5] opened 2015-11-19 04:56 UTC
Hello,

thank you for this great component (cross platform :+1: ),

is there any reason why **Wechat** does not appear in the sharing option (for ios) but appears in Android? As I understand it's possible to **exclude** some application to show up in the list, but how to add one?

Cheers.

**Comment by enieber** [comment] 2018-05-09 13:08
@sulliwane what version?

**Comment by yeomann** [comment] 2018-07-27 21:21
Hi there, the issue is being close. Since it is quite old. I suppose it might have been addressed in new releases of react native share. Please feel free to open it again, so that community can help you 😃

**Closed by yeomann** 2018-07-27 21:21 UTC
Labels: feature request
