### ISSUE TITLE
Unknown named module

### ISSUE THREAD

**Issue by leoabacade** [react-native-community/react-native-share#94] opened 2017-01-06 13:48 UTC
![15902631_120300001476447161_1277684824_o](https://cloud.githubusercontent.com/assets/2664504/21719635/bbca758e-d459-11e6-8c87-258f8a5dbd96.png)

pretty sure components are in right place.

<img width="315" alt="screen shot 2017-01-06 at 9 48 06 pm" src="https://cloud.githubusercontent.com/assets/2664504/21719653/e120f1fa-d459-11e6-89d4-5a2433dfe6f1.png">

**Comment by sibelius** [comment] 2017-07-11 13:29
@leoabacade do you still have this problem?

**Comment by yeomann** [comment] 2018-07-27 21:24
Hi there, the issue is being close. Since it is quite old. I suppose it might have been addressed in new releases of react native share. Please feel free to open it again, so that community can help you 😃

**Closed by yeomann** 2018-07-27 21:24 UTC
