### ISSUE TITLE
google plus share link error in android simulator

### ISSUE THREAD

**Issue by wzy535** [react-native-community/react-native-share#76] opened 2016-10-25 01:50 UTC
Hi,
I installed in android emulator ,but when touch google plus share ,It got this link in browse:
https://plus.google.com/share?url={url}.
Please help thanks in advance.

And another question, could you please support pinterest?

**Comment by natashache** [comment] 2017-11-06 16:21
I'm having the same problem on android. The actual url link somehow is not being passed on to google plus for sharing.

**Comment by jgcmarins** [comment] 2017-11-06 16:24
Maybe the problem is here: https://github.com/EstebanFuentealba/react-native-share/blob/master/android/src/main/java/cl/json/social/GooglePlusShare.java#L14

**Comment by natashache** [comment] 2017-11-06 16:27
@jgcmarins I don't know enough java to figure out what's wrong with that line. From what I can see, a similar line is in https://github.com/EstebanFuentealba/react-native-share/blob/master/android/src/main/java/cl/json/social/FacebookShare.java#L14. But somehow facebook sharing works.

**Comment by jgcmarins** [comment] 2017-11-06 16:33
You're right, this is the `default` link.

**Comment by natashache** [comment] 2017-11-06 17:00
@jgcmarins you are right. Changed lines 31-33 in GooglePlusShare.java to
```
    @Override
    protected String getDefaultWebLink() {
        return PLAY_STORE_LINK;
    }
```
It's now working correctly.

**Comment by jgcmarins** [comment] 2017-11-06 17:05
Great, @natashache! PRs are welcome :)

**Comment by nicholasess** [comment] 2018-05-13 14:49
I will close the issue, because has a suggestion in code by @natashache 
https://github.com/react-native-community/react-native-share/blob/master/android/src/main/java/cl/json/social/GooglePlusShare.java#L40

**Closed by nicholasess** 2018-05-13 14:49 UTC
