### ISSUE TITLE
v1.2.0 - link failure in iOS release mode

### ISSUE THREAD

**Issue by rollsroyc3** [react-native-community/react-native-share#504] opened 2019-05-26 20:08 UTC
## Ask your Question
I have been using this when testing on Android and iOS but now for some reason when compiling for production I keep getting the following error:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_InstagramStories", referenced from:
      objc-class-ref in libRNShare.a(RNShare.o)
ld: symbol(s) not found for architecture x86_64

Any idea what could be causing this? Ive tried older commits, forking and modifying, etc.. but no luck..

**Comment by MateusAndrade** [comment] 2019-05-26 20:49
Which version of share and react-native are you using?  

You Released a new version a few hours ago. Did you tried this version?

**Comment by MateusAndrade** [comment] 2019-05-26 23:46
Also you linked the project on ios?

**Comment by mikehardy** [comment] 2019-05-27 04:19
That's strange - I just attempted to integrate the 1.2.0 version and integrate it into my day-job app and I get the same error but for armv7 architecture. I have on conclusive information but I'm not sure react-native-share is in the clear yet, I have not successfully built the release version of my app with it yet. I'll report back if/when I have more but wanted to put this out there

**Comment by mikehardy** [comment] 2019-05-27 04:41
Okay, I just moved up a layer of abstraction from fastlane (my normal release build infra) to XCode direct and I get the exact same error described in the issue. I will look for a fix really quickly but as this is a build failure in a release I want to publish what I find as I find it, even it maybe generates irritating notification traffic (sorry if so).

**Comment by mikehardy** [comment] 2019-05-27 04:46
I have taken the liberty of updating the issue title to reflect what I **think** is the most precise description of the problem. Anyone feel free to revert it if it proves to be wrong later.

**Comment by mikehardy** [comment] 2019-05-27 04:58
Okay, I just reverted to react-native-share 1.1.3 with no other changes and iOS release mode builds and archives fine. 

@MateusAndrade  @jgcmarins  it is possible to `npm unpublish` and the 1.2.0 artifact should be unpublished, it is non-functional in iOS release builds. 

I will continue looking for solutions and hopefully we will have a 1.2.1 shortly, but 1.2.0 should not be consumed.

Anyone that currently has 1.2.0 should pin 1.1.3 in their dependencies until 1.2.0 is unpublished and/or this is sorted out.

Apologies to anyone affected.

**Comment by mikehardy** [comment] 2019-05-27 06:21
I have proposed a PR #505  to revert the change which causes the iOS archive failure. I'm not sure what is causing it and am out of time to diagnose further, sorry. If the PR is merged then a 1.2.1 is possible with everything but instagram stories, and it appears to archive correctly in my project

**Comment by MateusAndrade** [comment] 2019-05-27 09:55
> I have proposed a PR #505 to revert the change which causes the iOS archive failure. I'm not sure what part of #449 is causing it and am out of time to diagnose further, sorry. If the PR is merged then a 1.2.1 is possible with everything but instagram stories, and it appears to archive correctly in my project

This is strange, i will ser the last version on my dayli project and give a look at this error. @mikehardy you can help-me debugging the ios implementation?

**Comment by MateusAndrade** [comment] 2019-05-27 09:56
For anyone having trouble with ios, please PIN version @1.1.3.

**Comment by mikehardy** [comment] 2019-05-27 11:50
@MateusAndrade sorry - I'm about to hop on a plane and will be traveling most of the next two days, I used what time I had last night to investigate but couldn't find anything. My project definitely archives correctly at 1.1.3 and definitely has this error with 1.2.0. You can see it if you flip the mode from Debug to Release in your iOS scheme locally in XCode. I couldn't see anything that would cause it but there was some stackoverflow indicating it was perhaps that the new files weren't added to all the targets but when I checked it did not *seem* to be that. Unfortunately my XCode skills are not strong. @loga4 may have more information, as the original author of the PR

**Comment by loga4** [comment] 2019-05-27 12:00
@mikehardy Thanks for the mention.
@MateusAndrade I will try to look at the error today. But I definitely made some changes, but did not send PR. And i added an Android implementation.

**Comment by mikehardy** [comment] 2019-05-27 12:03
Awesome @loga4 - I still think we should revert here and push 1.2.1 to get everything but the affected PR out, and then as I mentioned elsewhere this must be some tiny bug. The iOS Instagram Stories PR *looks* good, it's just some silly (but show-stopping) XCode thing I'm sure. Hopefully that guess is true so it's an easy fix

**Comment by jgcmarins** [comment] 2019-05-27 15:44
Sorry for the late answer, but I got lost with Stale Bot notifications.

Interesting, we had something similar with Android: https://twitter.com/sseraphini/status/1133010302575009794

I'll try to merge @mikehardy PR and then unpublish v1.2.0.

Apologies to anyone affected.

**Comment by mikehardy** [comment] 2019-05-27 17:32
My previous revert was incomplete but I just got off a plane and had time to patch it up and force-push the branch the PR is based on, so it should be okay to merge for real now. I think this is different than the react-native template thing you linked, but who knows :-)

**Comment by jgcmarins** [comment] 2019-05-27 17:44
@mikehardy I took a look at #505 and didn't understood what could be causing this error.

Can someone test this 👇?
> I was searching for similar issues on other projects and i found this issue:
> 
> kmagiera/react-native-gesture-handler#387 (comment)
> 
> It looks similar to our problem. If anybody can give a try at the solution applied on this issue, this would help us a lot.

I also found something that could might be related: https://stackoverflow.com/questions/54515175/undefined-symbols-for-architecture-arm64-jsclasscreate

**Comment by mikehardy** [comment] 2019-05-27 17:57
No time left today sorry...

**Comment by jgcmarins** [comment] 2019-05-27 17:57
More about [JavaScriptCore.framework](https://github.com/facebook/react-native/issues/23183#issuecomment-458063622).

@rollsroyc3 could you provide more infos about your react native project? Like, RN version etc, running this command: https://github.com/react-native-community/cli/blob/master/docs/commands.md#info
Thanks.

**Comment by MateusAndrade** [comment] 2019-05-27 18:08
@jgcmarins im going to give a look at this later. but for now, it would be better publish a version without this following #505?

**Comment by jgcmarins** [comment] 2019-05-27 18:22
I am not sure if #505 is causing the error.

@loga4 are you using your fork, with Instagram stories support on production?

**Comment by loga4** [comment] 2019-05-27 19:09
@jgcmarins yes, i'm using fork on prod.
I uploaded the commit with android support to fork https://github.com/loga4/react-native-share/commit/0bfcc92e3ea0a63b7bd656102aed0547b45d27fd

rn 0.59.8
react 16.8.6

**Comment by MateusAndrade** [comment] 2019-05-27 19:29
> @jgcmarins yes, i'm using fork on prod.
> I uploaded the commit with android support to fork [loga4@0bfcc92](https://github.com/loga4/react-native-share/commit/0bfcc92e3ea0a63b7bd656102aed0547b45d27fd)
> 
> rn 0.59.8
> react 16.8.6

Anybody can try this fork please: https://github.com/MateusAndrade/react-native-share/tree/bugfix/ios-release-error

I run a archive, run on device and simulator without any problem .

**Comment by jgcmarins** [comment] 2019-05-27 19:42
> @jgcmarins yes, i'm using fork on prod.
> I uploaded the commit with android support to fork loga4@0bfcc92
> 
> rn 0.59.8
> react 16.8.6

Thank you!
I think our problem is that we've made a breaking change with RN version.
react-native-share v1.2.0 is only compatible with RN >= `0.59.0`

**Comment by jgcmarins** [comment] 2019-05-27 19:45
If there is any iOS specific issue on v1.2.0, it is right here: https://github.com/react-native-community/react-native-share/compare/v1.1.3...v1.2.0

**Comment by jgcmarins** [comment] 2019-05-27 19:56
iOS changes looks fine to me: https://github.com/react-native-community/react-native-share/compare/v1.1.3...v1.2.0#diff-9c2dcd04c2f1d35d7187af11b168ab8a

But maybe we've made a native change and it should be linked again (make sure it will only link once).

**Comment by MateusAndrade** [comment] 2019-05-27 20:41
Im testing using Pods, after run a rm -rf node_modules, pods, --reset-cache and im compiling without any problem. 

```
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 480.20 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 19, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-19 | ARM EABI v7a, android-21 | Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom, android-27 | Android TV Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.7 => 0.57.7
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native: 0.59.4
```

Also, my package.json: 

```json
  "dependencies": {
    "es6-promise": "^4.2.5",
    "fetch-intercept": "^2.3.1",
    "intl": "^1.2.5",
    "isomorphic-fetch": "^2.2.1",
    "lodash": "^4.17.11",
    "lottie-react-native": "^2.5.11",
    "moment": "^2.23.0",
    "prop-types": "^15.6.2",
    "react": "16.6.1",
    "react-native": "0.57.7",
    "react-native-animatable": "^1.3.2",
    "react-native-camera": "^1.10.0",
    "react-native-confirmation-code-input": "^1.0.4",
    "react-native-firebase": "5.2.1",
    "react-native-gesture-handler": "^1.0.15",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-linear-gradient": "^2.5.3",
    "react-native-masked-text": "^1.10.1",
    "react-native-orientation-locker": "^1.1.2",
    "react-native-picker-select": "^6.0.0",
    "react-native-share": "^1.2.0",
    "react-native-splash-screen": "^3.1.1",
    "react-native-tab-view": "^1.3.1",
    "react-native-vector-icons": "^6.2.0",
    "react-native-view-shot": "^2.5.0",
    "react-navigation": "^3.0.9",
    "react-navigation-fluid-transitions": "^0.3.1",
    "react-navigation-redux-helpers": "^2.0.9",
    "react-redux": "^5.1.1",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.7",
    "redux-thunk": "^2.3.0"
  },
```

Someone can test this on a project with manually linking?

**Comment by mikehardy** [comment] 2019-05-27 20:47
My project, where I was able to reproduce the error or not have the error during iOS archive with or without instagram stories, is using RN0.59.8 - nothing else was changing, so my experience via testing is that instagram stories does not work as is, and it is not related to react-native version. There must be a simple reason why it does not work (esp since a version of it is in production) but for the purposes of fixing a broken "most recent release" rapidly while real triage happens I think just reverting is best, so based on my testing experience that's what I proposed 🤷‍♂ . If my testing was somehow wrong and it was a react-native version thing I'll be surprised, but software does frequently surprise me so 🤷‍♂  again :-)

**Comment by rollsroyc3** [comment] 2019-05-28 13:06
Sorry was afk all holiday weekend. I ended rolling back to the commit before Instagram Stories was added, PR 449 I believe. Cleared node_modules/react-native-share and npm install. Worked fine. I can help test if you need anything else from me.

**Comment by MateusAndrade** [comment] 2019-05-29 03:11
> Sorry was afk all holiday weekend. I ended rolling back to the commit before Instagram Stories was added, PR 449 I believe. Cleared node_modules/react-native-share and npm install. Worked fine. I can help test if you need anything else from me.

You can try the version 1.2.0, looking at the links on XCode please? Also, you are manually linking the project or you are using cocoapods?

**Comment by jgcmarins** [comment] 2019-05-29 14:00
Done
https://github.com/react-native-community/react-native-share/releases/tag/v1.2.1
https://www.npmjs.com/package/react-native-share/v/1.2.1

**Closed by jgcmarins** 2019-05-29 14:00 UTC
Labels: bug, first seen issue, os: ios, question

**Comment by mikehardy** [comment] 2019-05-29 23:16
Confirming 1.2.1 archives in release mode correctly in testing

**Comment by MateusAndrade** [comment] 2019-05-29 23:46
> Confirming 1.2.1 archives in release mode correctly in testing

We still need to know what led to this error. hahahaha

@loga4 do you find anything that can led to this error?

**Comment by jgcmarins** [comment] 2019-05-30 03:33
> Confirming 1.2.1 archives in release mode correctly in testing

Thank you, @mikehardy!
We're now back to the game.

@loga4, I would love to have Instagram stories implementation back. Anything you need from me to help you dig into the problem, just ask.

**Comment by jgcmarins** [comment] 2019-05-30 03:57
I've asked on twitter: https://twitter.com/jgcmarins/status/1133945257131950085

**Comment by tara-singh-danu** [comment] 2022-10-19 07:15
Did someone found any solution?

**Comment by mikehardy** [comment] 2022-10-19 12:11
To a problem from 2019, 3 years ago? Yes I think everyone has moved on. You may try a brand new project with `npx react-native init ReactNativeShare && cd ReactNativeShare && yarn add react-native-share && npx pod-install && npx react-native run-ios --configuration Release` to see for your self. You tried that before requesting assistance to verify locally in a clean project, yes?

**Comment by luco** [comment] 2022-11-22 20:23
I'm getting this as well:

![image](https://user-images.githubusercontent.com/246373/203413881-02f0e88e-d18c-4aa6-ba74-802ddbfb10d2.png)

**Comment by mikehardy** [comment] 2022-11-27 01:10
@luco https://stackoverflow.com/help/how-to-ask - if you included information like described in that link someone may be able to help
