### ISSUE TITLE
Although Instagram App installed my device, share is not working. It is opening to App Store.

### ISSUE THREAD

**Issue by buraksak35** [react-native-community/react-native-share#388] opened 2018-10-24 08:18 UTC
### Expected behaviour
Open directly instagram app

### Actual behaviour
Open app store

### Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2
        API Levels: 22, 23, 26, 27, 28
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

### react-native-share
"react-native-share": "^1.1.2",

![ekran resmi 2018-10-24 11 34 07](https://user-images.githubusercontent.com/39245976/47417528-d4c0f000-d780-11e8-93b1-41100152bcda.png)

**Comment by mikehardy** [comment] 2018-10-24 14:31
Which was installed first? The app using RNS or instagram? I assume from the code snippet it is iOS? What device or emulator version and iOS version?

**Comment by buraksak35** [comment] 2018-10-26 05:39
> Which was installed first? The app using RNS or instagram? I assume from the code snippet it is iOS? What device or emulator version and iOS version?

İphone 5s , IOS 11.I have a button as "Share to instagram" when I click instagram should open . But appstore is opening

**Comment by mgiorgi-github** [comment] 2018-11-17 08:18
Same issue, all app (Facebook, Instagram and whatsapp) are not opened but the share module open app to Apple store.
I’ve tryed the code example and use “Share ui component” link

**Comment by mgiorgi-github** [comment] 2018-11-20 14:49
i've to pass image with local url path (file://) or base64?
Instagram open last image of my gallery, not the image i've selected, Facebook give error message (wrong url)

**Comment by jgcmarins** [comment] 2018-11-20 14:53
it works for both approaches
which error message are you experiencing when sharing at Facebook?

**Comment by mgiorgi-github** [comment] 2018-11-20 15:03
With my iPhone 6 iOS 12.1:
Instagram now open app but with wrong image
Facebook open the browser with error "href should represent a valid url"

Thanks

**Comment by jgcmarins** [comment] 2018-11-20 15:14
weird
can we have a repo to reproduce?

**Comment by mgiorgi-github** [comment] 2018-11-20 15:21
I can send my App.js file

**Comment by itsdante** [comment] 2019-02-15 19:09
> I had same issue,
> 
> Linking.canOpenURL work wrong.
> 
> i delete it :(. It's not a good idea but now it's working

Actually it still works, it's just that the link has changed, you need to use localIdentifier as an image/video path and OpenInEditor=1, this is what i currently use

let instagramURL = `instagram://library?OpenInEditor=1&LocalIdentifier=${identifier}`;
Linking.openURL(instagramURL);

**Comment by jgcmarins** [comment] 2019-02-15 19:46
@itsdante is there anything we can add to docs?

**Comment by itsdante** [comment] 2019-02-16 17:10
> @itsdante is there anything we can add to docs?

I think adding a basic explanation is enough and telling users how to retrieve the localidentifier from an image. **You cannot use a remote url to share the image** you need to save it to a local directory (i'm using cameraRoll) first then get the localidentifier, this can be acquired by splitting the result of cameraRoll.saveToCameraRoll(). But it should be noted that by using this custom url, users will be ask to share the media to either story or feed (i haven't find a way to directly go to feed yet), if you want to go directly to instagram stories, you should go and use the Share.Social.INSTAGRAM_STORIES.

Here's an example of my code 
`shareToInstagramIOS() {
    let mediaExt = this.state.videoUrl.split(".").pop();
    let mediaType = (mediaExt.toLowerCase() == 'jpg' || mediaExt.toLowerCase() == 'jpeg' || mediaExt.toLowerCase() == 'png') ? 'photo' : 'video';
    let path = RNFS.DocumentDirectoryPath + `/verikool${this.state.randomString}.${mediaExt}`;
    RNFS.downloadFile({
      fromUrl: this.state.videoUrl,
      toFile: path
    }).promise.then(() => {
      if (RNFS.exists(path)) {
        CameraRoll.saveToCameraRoll(path, mediaType)
          .then(imagePath => {
            let imageId = imagePath.split("id=").pop();
            let identifier = imageId.split("&")[0];
            let instagramURL = `instagram://library?OpenInEditor=1&LocalIdentifier=${identifier}`;
            Linking.openURL(instagramURL);
          })
          .catch(err => {
            Toast.show(err.message);
          })
      }
    })
      .catch(err => {
        Toast.show(err.message);
      });
  }`

I'm detecting the mediaType due to reason of cameraRoll.saveToCameraRoll() sometimes get messed up, it detected mkv / mp4 video extensions differently and saving it as an image


Hope this helps, i spent quite sometime tinkering with all of this and i don't want people scratching their heads and waste time on this

**Comment by dev2612** [comment] 2019-08-02 07:38
I resolved this issue today by adding this key in info.plist

<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>instagram://app</string>
	</array>


In the string tag  I had mentioned only instagram and it opened, instagram app store link and when ://app was added, it detected the installed instagram app and opened the app.

**Comment by jgcmarins** [comment] 2019-08-02 13:05
@dev2612 awesome!
We already have this on docs, step 6 of installation: https://github.com/react-native-community/react-native-share/blob/master/README.md#ios-install
Is there anything we should add to clarify?

I am closing the issue, just let me know if there is anything missing. Thanks.

**Closed by jgcmarins** 2019-08-02 13:05 UTC
Labels: first seen issue, help wanted

**Comment by xrzhuang** [comment] 2020-12-10 07:41
I am having this same issue I tried adding `<string>instagram://app</string>` to my `LSApplicationQueriesSchemes` but it did not work. I am using shareSingle to instagram. Pls help

**Comment by erikkjernlie** [comment] 2021-11-16 12:16
I accidentally had two keys for `LSApplicationQueriesSchemes` inside my info.plist, where the last one did not include the _instagram-stories_ value. This caused some overriding issues, and it worked after I removed one of the keys.
