### ISSUE TITLE
Sharing to Facebook Messenger

### ISSUE THREAD

**Issue by julienkessels** [react-native-community/react-native-share#274] opened 2018-06-02 15:55 UTC
Hello,
i've successfully added the lib to my project but I've been looking for an hour how to add Facebook Messenger to the options. 
Can anyone help me out?

Thanks!

**Comment by julienkessels** [comment] 2018-06-02 15:59
Maybe SMS/Messages is just not working on the simulator..

**Comment by jgcmarins** [comment] 2018-06-04 13:30
@julienkessels since this is not a bug, I am closing it.
You can share through Facebook Messenger using React Native share API: https://facebook.github.io/react-native/docs/share.html

**Closed by jgcmarins** 2018-06-04 13:30 UTC

**Comment by jgcmarins** [comment] 2018-06-04 13:31
Feature Request: https://github.com/react-native-community/react-native-share/issues/150

**Comment by Luckygirlllll** [comment] 2018-10-11 10:28
Hello, was this feature added to the lib? It's not possible to share links via react-native share in Android.

**Comment by kalraneeraj24550** [comment] 2018-12-26 05:05
// with this two lines am able to send link
const sharingUrl = 'www.google.com';
Linking.openURL(fb-messenger://share?link=${sharingUrl});

but anyone plz help how can i send only text message for example. "hello world". no link, no image only text message.

**Comment by abhinavremitly** [comment] 2019-11-24 22:52
> // with this two lines am able to send link
> const sharingUrl = 'www.google.com';
> Linking.openURL(fb-messenger://share?link=${sharingUrl});
> 
> but anyone plz help how can i send only text message for example. "hello world". no link, no image only text message.

@kalraneeraj24550 Were you able to find the solution to send a simple text message via fb-messenger? Asking because even I am looking for the same answer.
